[project]
name = "data-pipeline-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagger>=1.3.0",
]

[tool.uv.workspace]
members = ["libs/py-workflow", "apps/crm-ingestion-job", "libs/py-utils"]
